ASPStamp/Controllers/FormController.cs
using InvoiceStamp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace InvoiceStamp.Controllers
{
    public class FormController : Controller
    {
        // GET: Form
        public ActionResult Index()
        {
            // initialze Temp Directory
            string tempDirPath = Server.MapPath("~/Uploads/Templates/thumbs");
            if (!Directory.Exists(tempDirPath))
            {
                Directory.CreateDirectory(tempDirPath);
            }
            ViewData["templates"]= getTemplateList("");
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            string templateName;
            
            if (file.ContentLength > 0)
            {
                // save file
                templateName = Path.GetFileName(file.FileName).Replace(" ", "");                
                var militime = Globals.getCurrentMiliSecond();
                var fileName = militime + ".PDF";
                var fullPath = Path.Combine(Server.MapPath("~/Uploads/Templates"), fileName);
                file.SaveAs(fullPath);
                if(System.IO.File.Exists(Path.Combine(Server.MapPath("~/Uploads/Templates"), templateName)))
                {
                    System.IO.File.Delete(Path.Combine(Server.MapPath("~/Uploads/Templates"), templateName));
                }
                file.SaveAs(Path.Combine(Server.MapPath("~/Uploads/Templates"), templateName));

                // initialze Temp Directory
                string tempDirPath = Server.MapPath("~/Uploads/Templates/thumbs");
                if (!Directory.Exists(tempDirPath)) Directory.CreateDirectory(tempDirPath);
                if (!Directory.Exists(Server.MapPath("~/Uploads/Templates/thumbs/") + militime))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Uploads/Templates/thumbs/") + militime);
                }else
                {
                    string[] files=Directory.GetFiles(Server.MapPath("~/Uploads/Templates/thumbs/") + militime, "*.png");
                    foreach (string img_file in files) System.IO.File.Delete(img_file);
                }
                    
                string command = Server.MapPath("~/Libs/gs/gswin64c.exe");
                string temp_dir = Server.MapPath("~/Uploads/Templates/thumbs/") + militime + "/%d.png ";
                string parameter = "-sDEVICE=png16m -r480 -dDownScaleFactor=3 -o " + temp_dir + fullPath;
                Process proc = new Process();
                proc.StartInfo.FileName = command;
                proc.StartInfo.Arguments = parameter;
                proc.StartInfo.CreateNoWindow = true;
                proc.StartInfo.UseShellExecute = false;
                proc.Start();
                proc.WaitForExit();
                // preprocess 
                System.IO.File.Delete(fullPath);
                if (!Directory.Exists(Server.MapPath("~/Uploads/Templates/thumbs/") + templateName.Split('.')[0])){
                    Directory.CreateDirectory(Server.MapPath("~/Uploads/Templates/thumbs/") + templateName.Split('.')[0]);
                }else{
                    string[] files = Directory.GetFiles(Server.MapPath("~/Uploads/Templates/thumbs/") + templateName.Split('.')[0], "*.png");
                    foreach (string img_file in files) System.IO.File.Delete(img_file);
                }
                // copy
                string[] img_files = Directory.GetFiles(Server.MapPath("~/Uploads/Templates/thumbs/") + militime, "*.png");
                for(int i=0; i<img_files.Length; ++i)
                {
                    System.IO.File.Copy(Server.MapPath("~/Uploads/Templates/thumbs/") + militime+"/"+(i+1)+".png", Server.MapPath("~/Uploads/Templates/thumbs/") + templateName.Split('.')[0] + "/" + (i + 1) + ".png");
                }
                // delete all image in temp dir
                string[] t_files = Directory.GetFiles(Server.MapPath("~/Uploads/Templates/thumbs/") + militime, "*.png");
                foreach (string img_file in t_files) System.IO.File.Delete(img_file);
                Directory.Delete(Server.MapPath("~/Uploads/Templates/thumbs/") + militime);

                return new JsonResult { Data = getTemplateList(templateName) };
            }else{
                return View();
            }            
        }

        public List<string> getTemplateList(string templateName) {
            // get image file list  
            List<string> templateImgUrls = new List<string>();
            string thumbs_url = Server.MapPath("~/Uploads/Templates/thumbs/");
            string[] thumbs_dirs = Directory.GetDirectories(Server.MapPath("~/Uploads/Templates/thumbs"));
            string[] template_urls = Directory.GetFiles(Server.MapPath("~/Uploads/Templates"), "*.PDF");
            for (int i = 0; i< thumbs_dirs.Length; ++i)
            {
                string template_url, cur_flag = "0";
                template_url = Globals.ResolveServerUrl("/Uploads/Templates/" + Path.GetFileName(template_urls[i]), false);

                string[] files = Directory.GetFiles(thumbs_dirs[i], "*.png");
                string thumbs = "";
                foreach (string file in files)
                {
                    string aaa = "/Uploads/Templates/thumbs/" + file.Split('\\')[file.Split('\\').Length - 2] + "/" + file.Split('\\')[file.Split('\\').Length - 1];
                    thumbs = thumbs + "|" + Globals.ResolveServerUrl("/Uploads/Templates/thumbs/" + file.Split('\\')[file.Split('\\').Length - 2] + "/" + file.Split('\\')[file.Split('\\').Length - 1], false);
                }
                if (Path.GetFileName(template_urls[i]).Equals(templateName)) cur_flag = "1";
                templateImgUrls.Add(template_url + "," + thumbs + ","+ cur_flag);
            }
            return templateImgUrls;
        }

        [HttpPost]
        public ActionResult Delete(Form form)
        {
            string templateName =form.formName.Split('/')[form.formName.Split('/').Length - 2];
            if (Directory.Exists(Server.MapPath("~/Uploads/Templates/thumbs/"+ templateName)))
            {
                string[] files = Directory.GetFiles(Server.MapPath("~/Uploads/Templates/thumbs/")+ templateName, "*.png");
                foreach (string file in files) System.IO.File.Delete(file);
            }
            Directory.Delete(Server.MapPath("~/Uploads/Templates/thumbs/"+ templateName));
            if (System.IO.File.Exists(Path.Combine(Server.MapPath("~/Uploads/Templates"), templateName + ".PDF")))
            {
                System.IO.File.Delete(Path.Combine(Server.MapPath("~/Uploads/Templates"), templateName + ".PDF"));
            }
            return new JsonResult { Data = getTemplateList("") };
        }
    }
}

ASPStamp/Views/Form/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2></h2>

<div class="container">
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-10">
            <div class="row">                
                <div class="col-sm-6" style="width:62.5%; ">
                    <form id="template-upload-form" method="post" enctype="multipart/form-data">
                        <input name="file" id="file" type="file" class="btn" accept="application/PDF" />
                        <img id="preload-img" class="invisible" src="~/Images/preloading.gif" style="float: left; position: absolute; margin-top: -27.5px; margin-left:-10px" />
                    </form>
                </div>                        
                
                <div class="col-sm-4" style="width:37.5%; ">
                    <div class="dropdown" style="float: right;">
                        <button id="template-dropdown-btn" class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Form template <span class="caret"></span>
                        </button>
                        <ul id="template-menu" class="dropdown-menu">                            
                        </ul>
                    </div>
                </div>               
            </div>
            <div class="row">
                <a><span id="del-span" class="glyphicon glyphicon-remove invisible" style="float:right;cursor:pointer;margin-right: -16px;"></span></a>
                <div class="row" id="preivew-template-div">
                </div>                
            </div>
        </div>  
        <div class="col-sm-1"></div>      
    </div>    
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.form.js"></script>

<script>
    var form_list;

    $(document).ready(function () {
        @{
            var template_list = (List<string>)ViewData["templates"];
            string tt="";
            if (template_list.Count>0){
                tt= template_list[0];
                for (int i = 1; i < template_list.Count; ++i)
                {
                    tt = tt + "=" + template_list[i];
                }
            }
        }
        form_list = "@tt";
        form_list = form_list.split("=");
        loadingFormTemplate();
    });

    $("#file").on('drop', function (e) {
        $("#file").change();
    });

    $("#file").change(function () {
        if ($("#file").val().length <= 0) return;
        $("#template-upload-form").ajaxForm({
            url: "@Url.Action("Index", "Form")",
            beforeSend: function () {
                $('#preload-img').removeClass('invisible');
            },
            uploadProgress: function (event, position, total, percentComplete) { },
            error: function () {
                alert("Image upload error");
                //window.refresh();
            },
            success: function () { },
            complete: function (xhr) {
                //console.log(xhr.responseJSON);
                $('#preload-img').addClass('invisible');
                if (!Array.isArray(xhr.responseJSON)) return;
                form_list = xhr.responseJSON;
                loadingFormTemplate();
            }
        }).submit();
    });

    function loadingFormTemplate() {
        var template_list_html = '';
        for (var i = 0; i < form_list.length; ++i) {
            var template_name = form_list[i].split(',')[0].split('/')[form_list[i].split(',')[0].split('/').length - 1];
            template_name = template_name.split('.')[0];
            template_list_html = template_list_html + "<li id='template"+i+"'><a href='javascript:selectFormTemplate(" + i + ")'>" + template_name + "</a></li>";
            if (form_list[i].split(',')[2] == 1) selectFormTemplate(i);
        }
        $("#template-menu").html(template_list_html);
    }

    function selectFormTemplate(form_index) {
        if (form_list.length <= form_index) return;
        $("#template-dropdown-btn").html(form_list[form_index].split(',')[0].split('/')[form_list[form_index].split(',')[0].split('/').length - 1].split('.')[0] + " <span class='caret'></span>");
        var template_imgs = form_list[form_index].split(",")[1].split("|");
        var img_list_html = '';
        for (var i = 1; i < template_imgs.length; ++i) {
            img_list_html += "<img id='preview-template-img"+i+"' class='img-thumbnail' style='width:100%' src=" + template_imgs[i] + " />";
        }
        $("#stamp-list").html(img_list_html);
        //$("#preview-template-img").attr("src", form_list[form_index].split(',')[1]);
        $("#preivew-template-div").html(img_list_html);
        $("#del-span").removeClass('invisible');
    }

    $("#del-span").click(function () {
        if (!confirm("Delete Form ?")) return;
        $.ajax({
            type: 'POST',
            url: "@Url.Action("Delete","Form")",
            data: "{'formName':'"+$("#preview-template-img1").attr("src")+"'}",
            ajaxasync: true,
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (response) {
                form_list = response;
                loadingFormTemplate();
                $("#template-dropdown-btn").html("Form template <span class='caret'></span>");
                $("#preivew-template-div").html("");
                $("#del-span").addClass('invisible');
            },
            complete: function(){

            },
            error: function (e) {
                alert('Failed');
            }
        });
    });
</script>